POST  http://localhost:8080/forgetPassword HTTP/1.1
Content-Type: application/json

{
    "username": "hello123456",
    "visa_id": "FE1234567890",
    "birthday": "2023/05/01",
    "newpassword":"12345678",
    "confirmnewpass":"12345678" 
}