POST  http://localhost:8080/forgetPassword HTTP/1.1
Content-Type: application/json

{
    "username": "7",
    "visa_id": "abc123@",
    "birthday": "2023/05/09",
    "newpassword":"13",
    "confirmnewpass":"13" 
}